from src.domain.entities.user import User
from src.domain.exceptions import EmailAlreadyExistsError, PasswordLengthNotEnoughError
from src.domain.interfaces.hasher import Hasher
from src.domain.interfaces.jwt_provider import JWTProvider
from src.domain.interfaces.user_repository import UserRepository


class AuthService:
    """Authentication service for user registration and login"""

    def __init__(
        self, user_repository: UserRepository, jwt_provider: JWTProvider, hasher: Hasher
    ):
        self.user_repository = user_repository
        self.jwt_provider = jwt_provider
        self.hasher = hasher

    async def register(self, email: str, password: str) -> dict:
        """
        Register a new user and return JWT token

        Args:
            email: User's email address
            password: User's password (will be hashed)

        Returns:
            JWT token string

        Raises:
            EmailAlreadyExistsError: If email is already registered
        """
        if await self.user_repository.find_by_email(email) is not None:
            raise EmailAlreadyExistsError(email)

        password_min_length = 10

        if password.__len__() < password_min_length:
            raise PasswordLengthNotEnoughError(password_min_length)

        password = self.hasher.hash(password)

        # Create user entity
        user = User(
            id="",  # Will be generated by repository
            email=email,
            password=password,
        )

        # Save user to database
        user = await self.user_repository.create(user)
        accessToken = self.jwt_provider.generate_access_token(user.id)
        refreshToken = self.jwt_provider.generate_refresh_token(user.id)

        return {"accessToken": accessToken, "refreshToken": refreshToken}
