from typing import Optional
from src.domain.entities.user import User
from src.domain.exceptions import (
    EmailAlreadyExistsError,
    NonAuthorizedError,
    NotCorrectError,
    NotFoundError,
    PasswordLengthNotEnoughError,
    PasswordNotCorrectError,
    UserNotFoundError,
)
from src.domain.interfaces.email_verification_code_repository import (
    EmailVerificationCodeRepository,
)
from src.domain.interfaces.hasher import Hasher
from src.domain.interfaces.jwt_provider import JWTProvider
from src.domain.interfaces.random_name_generator import RandomNameGenerator
from src.domain.interfaces.refresh_token_repository import RefreshTokenRepository
from src.domain.interfaces.user_repository import UserRepository


class AuthService:
    """Authentication service for user registration and login"""

    def __init__(
        self,
        user_repository: UserRepository,
        jwt_provider: JWTProvider,
        hasher: Hasher,
        refresh_token_repository: RefreshTokenRepository,
        random_name_generator: RandomNameGenerator,
        email_verification_code_repository: EmailVerificationCodeRepository,
    ):
        self.user_repository = user_repository
        self.jwt_provider = jwt_provider
        self.hasher = hasher
        self.refresh_token_repository = refresh_token_repository
        self.random_name_generator = random_name_generator
        self.email_verification_code_repository = email_verification_code_repository

    async def change_password(self, current_user: User, token: str, new_password: str):
        verified = self.jwt_provider.verify_token(token)
        user_id = verified.get("user_id")

        if current_user.id != user_id:
            raise NonAuthorizedError()

        hashed_new_password = self.hasher.hash(new_password)
        current_user.password = hashed_new_password

        await self.user_repository.update(current_user)

    async def verify_change_password(self, current_user: User, code: str) -> str:
        verification_code = (
            await self.email_verification_code_repository.find_by_user_id(
                current_user.id
            )
        )

        if verification_code is None:
            raise NotFoundError()

        if verification_code.code != code:
            raise NotCorrectError()

        await self.email_verification_code_repository.delete_by_user_id(current_user.id)

        access_token = self.jwt_provider.generate_access_token(current_user.id)
        return access_token

    async def refresh_token(self, refresh_token: str) -> dict:
        payload = self.jwt_provider.verify_token(refresh_token)
        user_id: Optional[str] = payload.get("user_id")

        if user_id is None:
            raise UserNotFoundError()

        tokens = await self.refresh_token_repository.find_tokens_by_user_id(user_id)

        if tokens.__contains__(refresh_token) is False:
            raise NotFoundError()

        await self.refresh_token_repository.delete_by_user_id(user_id)

        access_token = self.jwt_provider.generate_access_token(user_id)
        refresh_token = self.jwt_provider.generate_refresh_token(user_id)

        await self.refresh_token_repository.create(refresh_token, user_id)

        result = {"accessToken": access_token, "refreshToken": refresh_token}

        return result

    async def login(self, email: str, password: str) -> dict:
        user = await self.user_repository.find_by_email(email)

        if user is None:
            raise UserNotFoundError()

        is_password_correct = self.hasher.verify(password, user.password)

        if is_password_correct is False:
            raise PasswordNotCorrectError()

        await self.refresh_token_repository.delete_by_user_id(user.id)

        access_token = self.jwt_provider.generate_access_token(user.id)
        refresh_token = self.jwt_provider.generate_refresh_token(user.id)

        await self.refresh_token_repository.create(refresh_token, user.id)

        return {"accessToken": access_token, "refreshToken": refresh_token}

    async def register(self, email: str, password: str) -> dict:
        if await self.user_repository.find_by_email(email) is not None:
            raise EmailAlreadyExistsError(email)

        password_min_length = 10

        if password.__len__() < password_min_length:
            raise PasswordLengthNotEnoughError(password_min_length)

        password = self.hasher.hash(password)

        # Create user entity
        user = User(
            id="",  # Will be generated by repository
            email=email,
            password=password,
            username=self.random_name_generator.generate(),
        )

        # Save user to database
        user = await self.user_repository.create(user)
        access_token = self.jwt_provider.generate_access_token(user.id)
        refresh_token = self.jwt_provider.generate_refresh_token(user.id)

        await self.refresh_token_repository.create(refresh_token, user.id)

        return {"accessToken": access_token, "refreshToken": refresh_token}
